ALTER TABLE customers ADD COLUMN IF NOT EXISTS cep TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS street TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS number TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS complement TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS neighborhood TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS state TEXT;
